version: '3'
services:
  newsletter:
    build: .
    restart: always
    environment:
      TZ: Europe/Paris
    env_file:
      - .env
    volumes:
      - ./newsletter.py:/app/newsletter.py